# -*- coding: utf-8 -*-
"""UCB_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19p2yrDbMrd_LN1ozutH0_RSIxBkjeFT1
"""

import numpy as np
import random
import time
import pandas as pd
import os
from collections import defaultdict

# Configuration
DIFFICULTY_MAP = {
    "easy": 0, "mid": 1, "medium": 2,
    "hard": 3, "advanced": 4, "exceptional": 5
}
DIFFICULTY_LIST = list(DIFFICULTY_MAP.keys())
MODALITY_TYPES = ['textual', 'image', 'auditory']
MODALITY_IDX = {k: i for i, k in enumerate(MODALITY_TYPES)}
MIN_QUESTIONS_PER_TYPE = 5
TOTAL_QUESTIONS = 20
CALIBRATION_QUESTIONS = 6
USER_DATA_FILE = "user_attempts.csv"

# Load and preprocess questions
def load_questions(file_path):
    df = pd.read_csv(file_path, encoding="ISO-8859-1")
    df = df.rename(columns=lambda x: x.strip())
    df = df.rename(columns={
        'ï»¿Question ID': 'ID',
        'Question Text': 'Question',
        'Difficulty Level': 'Difficulty',
        'Correct Answer': 'Answer',
        'Skill Sets': 'Skill',
        'Question Type': 'Type',
        'Answer Options': 'Options',
        'media_url': 'Media',
        'Associated Skill': 'AssociatedSkill'
    })

    df['Difficulty'] = df['Difficulty'].str.lower().map(DIFFICULTY_MAP)
    df = df.dropna(subset=['Difficulty'])
    df['Difficulty'] = df['Difficulty'].astype(int)
    df['Type'] = df['Type'].str.lower().str.strip()
    df['Type'] = df['Type'].apply(lambda x: x if x in MODALITY_TYPES else 'textual')
    return df.to_dict('records')

class AdaptiveIQTest:
    def __init__(self, user_id, questions):
        self.user_id = user_id
        self.questions = questions
        self.used_questions = set()
        self.question_history = []
        self.score = 0

        self.modality_perf = defaultdict(lambda: {'correct': 0, 'total': 0})
        self.diff_perf = defaultdict(lambda: {'correct': 0, 'total': 0})

        self.modality_rewards = np.zeros(len(MODALITY_TYPES))
        self.modality_counts = np.zeros(len(MODALITY_TYPES))
        self.difficulty_rewards = np.zeros(len(DIFFICULTY_MAP))
        self.difficulty_counts = np.zeros(len(DIFFICULTY_MAP))

        self.total_trials = 0
        self.load_past_attempts()


    def run(self, background):
        """Use background to initialize difficulty bias"""
        # Map background to initial difficulty boost
        difficulty_boost = {
            '1': 0.2,  # Business: slight boost to medium difficulty
            '2': 0.4,  # Social Sciences: stronger boost to easier questions
            '3': -0.1  # CS/Math: harder questions get initial boost
        }.get(background, 0)

        # Apply initial bias to medium difficulty
        self.difficulty_rewards[2] += difficulty_boost
        self.calibration_phase()
        self.adaptive_phase()
        self.display_results()
        self.store_results()

    def load_past_attempts(self):
        if os.path.exists(USER_DATA_FILE):
            df = pd.read_csv(USER_DATA_FILE)
            past = df[df['user_id'] == self.user_id]
            if not past.empty:
                print(f" Previous attempts found for user '{self.user_id}' — applying reinforcement bias")
                for _, row in past.iterrows():
                    modality = row['modality']
                    difficulty = int(row['difficulty'])
                    reward = float(row['reward'])
                    self.update_estimates(self.modality_rewards, self.modality_counts, MODALITY_IDX[modality], reward)
                    self.update_estimates(self.difficulty_rewards, self.difficulty_counts, difficulty, reward)

    def _adjust_difficulty_bias(self, current_difficulty):
        """Dynamically adjust difficulty rewards based on performance"""
        correct = self.diff_perf[current_difficulty]['correct']
        total = self.diff_perf[current_difficulty]['total']

        if total == 0:
            return

        success_rate = correct / total

        # Boost adjacent difficulties based on performance
        if success_rate < 0.4 and current_difficulty > 0:
            self.difficulty_rewards[current_difficulty-1] += 0.15
        elif success_rate > 0.75 and current_difficulty < len(DIFFICULTY_LIST)-1:
            self.difficulty_rewards[current_difficulty+1] += 0.15

    def ucb_select(self, estimates, counts):
        self.total_trials += 1
        if (counts == 0).any():
            return random.choice(np.where(counts == 0)[0])
        return np.argmax(estimates + 2 * np.sqrt((2 * np.log(self.total_trials)) / counts))

    def update_estimates(self, estimates, counts, index, reward):
        counts[index] += 1
        estimates[index] += (reward - estimates[index]) / counts[index]

    def normalize_reward(self, r):
        """Updated to preserve negative rewards"""
        return max(-1.0, min(1.0, r / 3))  # Scaled to [-1, 1]

    def assign_reward(self, correct, time_taken, difficulty):
        base = 1 if correct else -1
        time_penalty = min(time_taken / 10, 1)
        return (base - time_penalty) * (1.0 + 0.1 * difficulty)

    def select_question(self):
        m_idx = self.ucb_select(self.modality_rewards, self.modality_counts)
        d_idx = self.ucb_select(self.difficulty_rewards, self.difficulty_counts)
        modality = MODALITY_TYPES[m_idx]
        filtered = [q for q in self.questions if q['Type'] == modality and str(q['ID']) not in self.used_questions]
        exact = [q for q in filtered if q['Difficulty'] == d_idx]
        if exact:
            return random.choice(exact)
        return random.choice(filtered) if filtered else None

    def calibration_phase(self):
        print("\n Calibration Phase")
        for modality in MODALITY_TYPES:
            cands = [q for q in self.questions if q['Type'] == modality and str(q['ID']) not in self.used_questions]
            sample_size = min(2, len(cands))
            if sample_size == 0:
                continue
            qs = random.sample(cands, sample_size)
            for q in qs:
                self.used_questions.add(str(q['ID']))
                user_ans, correct_ans = self.present_question(q, len(self.question_history))
                correct = user_ans.lower() == correct_ans.lower()
                self.score += 1 if correct else 0
                self.question_history.append((q, correct))

                # Track performance
                self.modality_perf[q['Type']]['total'] += 1
                self.modality_perf[q['Type']]['correct'] += int(correct)
                self.diff_perf[q['Difficulty']]['total'] += 1
                self.diff_perf[q['Difficulty']]['correct'] += int(correct)

                reward = self.assign_reward(correct, 0, q['Difficulty'])
                norm_reward = self.normalize_reward(reward)
                self.update_estimates(self.modality_rewards, self.modality_counts, MODALITY_IDX[q['Type']], norm_reward)
                self.update_estimates(self.difficulty_rewards, self.difficulty_counts, q['Difficulty'], norm_reward)
                self._adjust_difficulty_bias(q['Difficulty'])

    def present_question(self, q, idx):
        print(f"\nQuestion {idx+1}/{TOTAL_QUESTIONS} [{q['Type'].capitalize()} | {DIFFICULTY_LIST[q['Difficulty']].capitalize()}]")
        print(q['Question'])
        if pd.notna(q.get('Media')) and str(q['Media']).strip():
            print(f"Media: {q['Media']}")
        options = [opt.strip() for opt in str(q['Options']).split(',') if opt.strip()]
        if q['Answer'] not in options:
            options.append(q['Answer'])
        options = list(set(options))
        random.shuffle(options)
        letters = "ABCDEF"[:len(options)]
        opt_map = {l: o for l, o in zip(letters, options)}
        for l, o in opt_map.items():
            print(f"{l}. {o}")
        while True:
            ans = input(f"Your answer ({'/'.join(letters)}): ").strip().upper()
            if ans in opt_map:
                break
        print("✅ Correct!" if opt_map[ans].lower() == q['Answer'].lower() else f"❌ Incorrect. Correct answer was: {q['Answer']}")
        return opt_map[ans], q['Answer']

    def adaptive_phase(self):
        print("\n🚀 Adaptive Phase")
        while len(self.question_history) < TOTAL_QUESTIONS:
            q = self.select_question()
            if not q:
                break
            self.used_questions.add(str(q['ID']))
            start = time.time()
            user_ans, correct_ans = self.present_question(q, len(self.question_history))
            time_taken = time.time() - start
            correct = user_ans.lower() == correct_ans.lower()
            self.score += 1 if correct else 0
            self.question_history.append((q, correct))

            self.modality_perf[q['Type']]['total'] += 1
            self.modality_perf[q['Type']]['correct'] += int(correct)
            self.diff_perf[q['Difficulty']]['total'] += 1
            self.diff_perf[q['Difficulty']]['correct'] += int(correct)

            reward = self.assign_reward(correct, time_taken, q['Difficulty'])
            norm_reward = self.normalize_reward(reward)
            self.update_estimates(self.modality_rewards, self.modality_counts, MODALITY_IDX[q['Type']], norm_reward)
            self.update_estimates(self.difficulty_rewards, self.difficulty_counts, q['Difficulty'], norm_reward)
            self._adjust_difficulty_bias(q['Difficulty'])

    def display_results(self):
        iq_score = 100 + (self.score * 1.5)
        iq_score = max(70, min(140, iq_score))
        print(f"\n🧠 Estimated IQ Score: {int(iq_score)}")
        print("\n📊 Modality Performance:")
        for mod in MODALITY_TYPES:
            d = self.modality_perf[mod]
            if d['total']:
                print(f"- {mod.capitalize()}: {d['correct']}/{d['total']} ({(d['correct']/d['total'])*100:.1f}%)")
        print("\n📈 Difficulty Performance:")
        for diff in sorted(self.diff_perf):
            d = self.diff_perf[diff]
            if d['total']:
                name = DIFFICULTY_LIST[diff]
                print(f"- {name.capitalize()}: {d['correct']}/{d['total']} ({(d['correct']/d['total'])*100:.1f}%)")

    def store_results(self):
        rows = []
        for q, correct in self.question_history:
            reward = self.assign_reward(correct, 0, q['Difficulty'])
            rows.append({
                'user_id': self.user_id,
                'question_id': q['ID'],
                'modality': q['Type'],
                'difficulty': q['Difficulty'],
                'correct': int(correct),
                'reward': reward
            })
        df = pd.DataFrame(rows)
        if os.path.exists(USER_DATA_FILE):
            df.to_csv(USER_DATA_FILE, mode='a', header=False, index=False)
        else:
            df.to_csv(USER_DATA_FILE, index=False)

    def run(self, background):
        self.calibration_phase()
        self.adaptive_phase()
        self.display_results()
        self.store_results()

# Main Execution
# Main Execution
if __name__ == "__main__":
    questions = load_questions("Example data.csv")
    print("Welcome to the Adaptive IQ Test")
    user_id = input("Enter your username: ").strip()

    # Keep background selection
    print("Select your background:")
    print("1. Business\n2. Social Sciences\n3. CS & Math")
    bg = input("Enter 1-3: ").strip()

    test = AdaptiveIQTest(user_id, questions)
    test.run(bg)  # Pass background to run()

    while True:
        again = input("\nWould you like to play again? (y/n): ").strip().lower()
        if again == 'y':
            test = AdaptiveIQTest(user_id, questions)
            test.run(bg)  # Pass background here too
        else:
            break

